name: Test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v2.6.2-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run golangci-lint
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: golangci-lint run --timeout=3m

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git
        run: apk add --no-cache git

      - name: Run tests
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: go test ./...
